### ISSUE TITLE
Add escape hatch for redirected sites

### ISSUE THREAD

**Issue by shawnbot** [SFDigitalServices/archive#19]
The "escape hatch" is how we'll route traffic _back_ to the original site on Pantheon if, for some reason, the redirect and/or archive logic isn't working properly, i.e.:

- Explicit redirects from `sftreasureisland.org` to `sf.gov` will continue to work without interruption
- Any URIs without explicit redirects will be routed to the Archive-It snapshot of that URL

If either of those features isn't working, the escape hatch will allow us to route all of the `sftreasureisland.org` requests back to the canonical live server, [live-treasure-island.pantheonsite.io](https://live-treasure-island.pantheonsite.io/).

This is probably best done in the site configuration files, e.g. for Treasure Island:

```yaml
archive:
  collection_id: 18901
  base_url: https://sftreasureisland.org

# ...

fallback:
  base_url: https://live-treasure-island.pantheonsite.io/
  enabled: false
```

I don't know if "fallback" or "passthrough" is the right name for the key, but whatever it is needs to define both whether it (the "escape hatch") is enabled and where (the URL) to redirect/proxy to. Another way we could structure it is to have a top-level `enabled` flag that we would flip to `false` to disable archive redirects and instead pass through every request to the `live.base_url`:

```yaml
enabled: true
live:
  base_url: https://live-treasure-island.pantheonsite.io/
```
