### ISSUE TITLE
Enable path-based routing for sfgov.org

### ISSUE THREAD

**Issue by shawnbot** [SFDigitalServices/archive#20]
Before we can start taking over routing for sfgov.org sites, we need the ability to route by both hostname(s) and path. Currently, sites can respond to one or more hostnames only, and requests that aren't handled by explicit redirects will go to the archive.

Rather than just being hostname-based, sites should be able to route from specific URL patterns, including the path. This could be inferred from the base URL in a site's config, and if the request path doesn't match that path prefix the site router will just `next('router')`. In configurations it might look like:

```yaml
# bac.yml
base_url: https://sfgov.org/bac/

# arts-commission.yml
base_url: https://sfgov.org/arts/
```

Then each site router would be mounted at the `pathname` of the base URL, i.e.

```js
app.use(site.baseUrl.pathname, site.createRouter())
```
