### ISSUE TITLE
Enable redirects with or without trailing slashes

### ISSUE THREAD

**Issue by shawnbot** [SFDigitalServices/archive#22]
This might need to happen on a per-redirect-map basis, e.g.

```yaml
redirects:
  - file: redirects.tsv
    trailing-slashes: true
  - map:
      /resources: https://sf.gov/resources
    trailing-slashes: true
```
